---
- name: udpate meraki ms switchports
  hosts: localhost
  vars:
    auth_key: "{{ auth }}"
    org_name: "{{ org }}"

  tasks:
    - name: include variables for switches
      include_vars:
        file: switches.yaml
        name: switches

    - name: Update information about a device.
      meraki_device:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_name: "{{ network_name }}"
        state: present
        serial:  "{{ serial_no }}"
        name: "{{ device_name }}"
        address: Bothell, WA
        lat: 41.948038
        lng: -87.65568
        tags: cicd
      register: updated_switch