---
- name: udpate meraki ms switchports
  hosts: localhost
  vars:
    auth_key: "{{ auth }}"
    org_name: "{{ org }}"

  tasks:
    - name: include variables for devices
      include_vars:
        file: switches.yaml
        name: switches

    - name: Update information about a device.
      meraki_device:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_name: "{{ item.value.network_name }}"
        state: present
        serial:  "{{ item.value.serial_no }}"
        name: "{{ item.value.device_name }}"
        address: Bothell, WA
        lat: 41.948038
        lng: -87.65568
        tags: "{{ item.value.tags }}"
      register: update_switch
      loop: "{{ lookup('dict', switches, wantlist=True) }}"