---
- name: udpate meraki ms switchports
  hosts: localhost
  vars:
    auth_key: "{{ auth }}"
    org_name: "{{ org }}"

  tasks:
    - name: include variables for devices
      include_vars:
        file: devices.yaml
        name: devices

    - name: include variables for addresses
      include_vars:
        file: addresses.yaml
        name: addresses

    - name: Update information about a device.
      meraki_device:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        net_name: "{{ network_name }}"
        state: present
        serial:  "{{ serial_no }}"
        name: "{{ device_name }}"
        address: 24004 26th DR SE, Bothell, WA
        lat: 41.948038
        lng: -87.65568
        tags: recently-added
      register: updated_switch